Integrado con Demonep y Logep. Faltan pasos 5,7 y 8.

diff --git a/installer/Grupo07/Initep b/installer/Grupo07/Initep
--- a/installer/Grupo07/Initep
+++ b/installer/Grupo07/Initep
@@ -1,15 +1,68 @@
 #!/bin/bash
 
-#Recibe un campo del config file como parámetro y devuelve el valor de ese campo
-#el archivo de configuracion debe ser de la forma
-#campo1 valor1
-#campo2 valor2
-#grep "GRUPO" dirconf/Instalep.conf | cut -f2 -d" "
-function get_var
-{
-	grep $1 $CONFIG_FILE | cut -f2 -d" "
 
+#**************** DECLARACION DE FUNCIONES ****************#
+
+
+#Recibe un campo del config file como parámetro y devuelve su valor
+#el archivo de configuracion debe ser de la forma
+#campo1=valor1=sarasa
+#campo2=valor2=otros=campos
+#-m1 busca la primera aparicion
+get_var()
+{
+	grep -m1 $1 $CONFIG_FILE | cut -d '=' -f 2
 }
+
+#$1=valor, $2=nombre de la variable
+#Valida si la variable tiene asignada algun valor, sino muestra mensaje y termina el programa
+isset_var() {
+	if [ -z "$1" ] 
+	then 
+		echo "No se puede inicializar la variable $2" 
+		exit 1
+	fi
+}
+
+#Valida el SetReadeable
+validateSetReadeable() {
+	if [ "$1" != "0" ] 
+	then
+		logMsg "ERROR: no se puede asignarle permiso de escritura a $2"	
+		exit 1
+	fi
+}
+
+
+#Setea en readeable el archivo pasado por parámetro
+#Devuelve 0 si todo va bien, !=0 en caso contrario
+setReadeable() {
+	if ! test -r $1
+	then 
+		#TODO: LOG ARCHIVO NO TIENE PERMISOS NECESARIOS
+		logMsg "Asignando permiso de escritura a $2" 
+		chmod -f +r $1
+		validateSetReadeable "$?" $2
+	fi
+}
+
+#Recibe un mensaje y lo guarda en el log del comando 
+logMsg() {
+	echo "$1"
+	#echo "¿Desea efectuar la activacion de Demonep? s/n"
+	$DIRBIN/Logep "$COMMAND" "$1"
+}
+
+iniciar_daemonep() {
+	$DIRBIN/Demonep
+}
+
+
+#**************** COMIENZO DEL SCRIPT ****************#
+
+
+
+export COMMAND="INITEP"
 
 CONFIG_FILE=$1 #guarda en una variable el archivo Instalep.conf recibido por parametro
 
@@ -26,34 +79,55 @@ then
 	exit 1
 fi
 
+
 #1: veo si ya fue iniciado el ambiente
 if [ "$ENVIRONMENT_ISSET" = "true" ]
 then
-	echo "Ambiente ya inicializado, para reiniciar termine la sesión e ingrese nuevamente"
-	#TODO: GUARDAR EN LOG
+	logMsg "Ambiente ya inicializado, para reiniciar termine la sesión e ingrese nuevamente"
 	exit 1 #termina la ejecucion con 1 para indicar error
 else
-	echo "INICIAR"
 	export ENVIRONMENT_ISSET="true"
-
 fi
 
-#2: SETEAR LAS VARIABLES DE AMBIENTE
 
-GRUPO=$(get_var "GRUPO")
-DIRBIN=$(get_var "DIRBIN")
-DIRMAE=$(get_var "DIRMAE")
-DIRREC=$(get_var "DIRREC")
-DIROK=$(get_var "DIROK")
-DIRPROC=$(get_var "DIRPROC")
-DIRINFO=$(get_var "DIRINFO")
-DIRLOG=$(get_var "DIRLOG")
+#2: SETEAR LAS VARIABLES DE AMBIENTE
+export GRUPO=$(get_var "GRUPO")
+export DIRBIN=$(get_var "DIRBIN")
+export DIRMAE=$(get_var "DIRMAE")
+export DIRREC=$(get_var "DIRREC")
+export DIROK=$(get_var "DIROK")
+export DIRPROC=$(get_var "DIRPROC")
+export DIRINFO=$(get_var "DIRINFO")
+export DIRLOG=$(get_var "DIRLOG")
+
+isset_var "$GRUPO" "GRUPO"
+isset_var "$DIRBIN" "DIRBIN"
+isset_var "$DIRMAE" "DIRMAE"
+isset_var "$DIRREC" "DIRREC"
+isset_var "$DIROK" "DIROK"
+isset_var "$DIRPROC" "DIRPROC"
+isset_var "$DIRINFO" "DIRINFO"
+isset_var "$DIRLOG" "DIRLOG"
 
 
 #3: CHEQUEAR LOS PERMISOS
-#no sé a qué archivos se refiere pero se valida con test como figura en la línea 23
-#documentación útil: http://tldp.org/LDP/abs/html/fto.html
+#Archivos DIRMAE/centros.csv, provincias.csv y trimestres.csv
+setReadeable "DIRMAE/centros.csv" "centros.csv"
+#setReadeable "DIRMAE/provincias.csv" "provincias.csv"
+#setReadeable "DIRMAE/trimestres.csv" "trimestres.csv"
 
-exit 0
+MSG="¿Desea efectuar la activacion de Demonep? s/n"
+logMsg "$MSG"
+read start_demonep
+if [ $start_demonep = "s" ]
+then
+	MSG="Si: Iniciando Demonep..."
+	logMsg "$MSG"
+	iniciar_daemonep	
+else
+	MSG="No: Saliendo de la aplicación"
+	logMsg "$MSG"
+fi
 
+exit $?
 
